edition: 1.0.0           #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: vaultwarden-alicloud           #  项目名称
access: default        #  秘钥别名

services:
  vaultwarden: # 模块名称
    component: devsapp/fc # 组件名称
    props: # 组件的属性值
      region: {{ region }} # 地域
      service: # 服务配置
        name: vaultwarden-fc-service # service名称
        description: vaultwarden fc component # Service的简短描述
        internetAccess: true # 设为true让function可以访问公网
        vpcConfig: auto
        nasConfig: auto # NAS配置, 配置后function可以访问指定NAS
      function: # 函数配置
        name: vaultwarden-fc # function名称
        description: 'vaultwarden for aliyun fc' # function的简短描述 
        memorySize: 512 # function的内存规格
        runtime: custom-container # 运行时
        timeout: 7200 # function运行的超时时间
        caPort: 80 # CustomContainer/Runtime指定端口
        customContainerConfig: # 自定义镜像配置
          image: {{ acrRegistry }} # 容器镜像仓库地址
        environmentVariables: # 环境变量
          DATA_FOLDER: '/mnt/auto'
      triggers: # 触发器配置
        - name: httpTrigger # 触发器名称
          type: http # 触发器类型
          config: # 触发器配置，包括OSS触发器, Log触发器, Log触发器, Timer触发器, Http触发器, MNS触发器, CDN触发器
            authType: anonymous # 鉴权类型，可选值：anonymous、function
            disableURLInternet: false # 是否禁用公网访问 URL
            methods: # HTTP 触发器支持的访问方法，可选值：GET、POST、PUT、DELETE、HEAD
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: '/*'
              methods:
                - GET
                - POST
                - PUT
                - DELETE