name: Push Vaultwarden Image to Aliyun ACR
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push the Docker image
        run: |
          docker version
          # 拉取 Vaultwarden 镜像
          docker pull vaultwarden/server:alpine
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ${{ secrets.REGISTRY_URL }}
          docker tag vaultwarden/server:alpine ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/vault:alpine
          # 推送镜像到镜像仓库
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/vault:alpine
